### ISSUE TITLE
Minio failed to upgrade 1.6 to 1.7

### ISSUE THREAD

**Issue by i-chvets** [canonical/minio-operator#108]
Minio failed to upgrade with error message:
```
ERROR Juju on containers does not support updating storage on a statefulset.
The new charm's metadata contains updated storage declarations.
You'll need to deploy a new charm rather than upgrading if you need this change.
 not supported (not supported)
```

[Jira](https://warthogs.atlassian.net/browse/KF-1102)

**Comment by DnPlas** [comment]
I am able to reproduce this issue after refreshing minio `ckf-1.6/stable` to `latest/edge`. This looks like something out of the control of Charmed Kubeflow though. Will investigate more.

**Comment by DnPlas** [comment]
Looking at the error message, it seems like the latest `metadata.yaml` contains "updated storage declarations", doing a bit of research I see [this](https://github.com/canonical/minio-operator/commit/981ad49ad356efffc454f8fe8abb69d5752d78b9) commit may be causing this disruption. I will try to remove that setting and see if I can upgrade afterwards.

**Comment by i-chvets** [comment]
RE: Minio upgrade story. I managed to get data across from old to new charm. However, it was done without scaling Minio to zero and than back up to one, i.e. there is a possibility of data inconsistency due to someone or some service accessing Minio when data migration is happening.

**Comment by i-chvets** [comment]
> Looking at the error message, it seems like the latest `metadata.yaml` contains "updated storage declarations", doing a bit of research I see [this](https://github.com/canonical/minio-operator/commit/981ad49ad356efffc454f8fe8abb69d5752d78b9) commit may be causing this disruption. I will try to remove that setting and see if I can upgrade afterwards.

Yes. That was done to accommodate request to have minimal storage for Minio in gateway mode. But if it breaks user experience, I think we should revert it.

**Comment by i-chvets** [comment]
What actually worries me is that when I scale Minio down using K8S API:
```
kubectl scale statefulset minio -n kubeflow --replicas=0
```
Then back up again:
```
kubectl scale statefulset minio -n kubeflow --replicas=1
```
All data from that PVC disappears.
So, if K8S decides to scale down our deployments for some reason, the data on the storage will be wiped out on scale up.

**Comment by i-chvets** [comment]
First version https://github.com/canonical/bundle-kubeflow/blob/kf-1089-doc-upgrade-guide-1.6-1.7/docs/upgrade-guide-1.6-to-1.7.md

**Comment by i-chvets** [comment]
Works. Verified in latest upgrade. (After changed reverted)
