### ISSUE TITLE
action to obtain secret-key

### ISSUE THREAD

**Issue by rgildein** [canonical/minio-operator#15]
There should be an action to obtain a secret key that has been randomly generated and is set [here](https://github.com/canonical/minio-operator/blob/2a91ff61f5ece0edc15beaa2af5ab528391c2cc6/src/charm.py#L35) as the default.

**Comment by gogaaa** [comment]
"MINIO_ACCESS_KEY": self.config["access-key"], 
adding this line to charm.py will allow to get acces and secret key fom config file

**Comment by r-f-g** [comment]
Yes, I know.  I have no problem getting the secret key from relation with Minio. Howerver I need to have access to the secret key in the CLI as well.

**Comment by gogaaa** [comment]
BTW is there any way to create tenant in minio operator by not using GUI but on backend using CLI

**Comment by r-f-g** [comment]
I'm not aware that this could be done right now. Maybe it could be done with this [plugin](https://docs.min.io/minio/k8s/tenant-management/deploy-minio-tenant.html), but I'm not an expert here.
