### ISSUE TITLE
Minio Scaling - adding multiple units to the Minio breaks it

### ISSUE THREAD

**Issue by Barteus** [canonical/minio-operator#73]
The Minio clustering requires additional configuration / different startup of the service. (https://min.io/docs/minio/kubernetes/upstream/operations/concepts.html#id5)

When multiple Minio Pods are created then each works as a different application. Additionally, because they are behind the same Service it looks like buckets and data disappear between calls.

**Comment by DnPlas** [comment]
Minio is getting replaced, we are not prioritising this issue anymore.
