### ISSUE TITLE
Integration tests are still using 1.21 microk8s instead of 1.24 for Kubeflow 1.6

### ISSUE THREAD

**Issue by Barteus** [canonical/minio-operator#74]
In the integration tests config microk8s 1.21 is used like in Kubeflow 1.4 but we can leverage 1.24 kubernetes now.

https://github.com/canonical/minio-operator/blob/368f707ee3e6df3f636ac2a8622743dc3e43dc80/.github/workflows/integrate.yaml#L61

**Comment by i-chvets** [comment]
Fixed by commit c1afea0. Closing.
